// ADMIN CONSTANTS

const UPDATE_TOKEN = 'UPDATE_TOKEN';
const SET_USER = 'SET_USER';

// FEED CONSTANTS

const UPDATE_FEED = 'UPDATE_FEED';
const ADD_WANTS = 'ADD_WANTS';
const SET_NEXT_PAGE_URL = 'SET_NEXT_PAGE_URL';

// FILTERS CONSTANTS

const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_FILTERS = 'SET_FILTERS';

export { 
    UPDATE_TOKEN,
    SET_USER, 
    UPDATE_FEED, 
    ADD_WANTS, 
    SET_NEXT_PAGE_URL,
    SET_CATEGORIES,
    SET_FILTERS 
};